geoadmin/service-stac

.gitignore
Makefile
buildspec.yml
project/app/admin.py
project/app/apps.py
project/app/models.py
project/app/tests.py
project/app/views.py
project/manage.py
project/project/settings.py
requirements.txt

Added CI integration for automated build and testing

CI integration

---

project/app/urls.py
project/app/views.py
project/project/urls.py

- Changed the landing page to be found under "api/stac/v0.9"
- added a simple "checker"-endpoint

Added 'checker' endpoint, changed landing page to '/api/stac/v0.9'

---

.isort.cfg
Makefile
dev_requirements.txt
project/config/settings.py
project/config/urls.py
project/stac_api/urls.py
project/wsgi.py
requirements.txt
tests/unit/test_landing_page.py

Added isort as mentioned in our geoadmin/doc-guideline and formated the
code to follow the import sorting.

Added isort to make format target

---

Makefile

Added Django targets to the help section of the Makefile
Capitalized all headers in the help section of the Makefile, in order to be consistent (most of the section headers were in capitals already).

Added Django targets to the help section

---

README.md

The badge changed on codebuild probably because the project has been re-created.

Fixed codebuild patch

---

Dockerfile
Makefile
Pipfile
Pipfile.lock
app/config/settings_dev.py
app/config/settings_prod.py
app/config/urls.py
app/middleware/debug_toolbar.py
buildspec.yml
docker-compose.yml

debug_toolbar is a handy add-on that's useful for debugging. I propose to install it since login fails on `bgdi-dev` due to a missing csrf token so it would be useful to debug http headers and stuff

adding django_debug toolbar

---

app/stac_api/admin.py
app/stac_api/models.py

Added missing admin pages and fixed a bug in provider.roles validation

BGDIINF_SB-1365: Added missing admin pages

---

Makefile
app/config/settings_dev.py
app/config/settings_prod.py
app/stac_api/apps.py
app/stac_api/models.py
app/stac_api/views.py
app/tests/database.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_items_endpoint.py
app/tests/test_serializer.py
spec/Makefile
spec/README.md
spec/base.yml
spec/components/parameters.yml
spec/components/responses.yml
spec/components/schemas.yml
spec/paths.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

Implemented a cursor pagination that matchs the STAC API spec.
Also fixed a bug in the collection model when creating a collection from admin page.

BGDIINF_SB-1374: implemented cursor pagination

---

spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

adding the missing `start_datetime` and `end_datetime`

adding missing start_datetime and end_datetime

---

README.md

Added some tipps about how to handle the db migration

Added documentation about db migration

---

app/middleware/debug.py

fixes the error in `make serve`

BGDIINF_SB-1430: bugfix for logging middleware

---

app/stac_api/models.py

When updating an item, the bbox of the collection may change.
But only when the geometry of the item will change, this may be.
So this improvement checks if the geometry has changed.

fix_BGDIINF_SB-1333: improve performance when updating an item

---

app/stac_api/views.py
app/tests/test_items_endpoint.py
spec/components/parameters.yml
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

BGDIINF_SB-1412: filter items by bbox

---

app/stac_api/models.py

When working on unit tests for updating the `*temporal* extent`, I noticed problems of the `*spatial* extent`, when the last item of a collection is deleted. This PR is intended to fix it ;-)

fixed issue with update of the spatial extent

---

spec/components/parameters.yml
spec/components/responses.yml
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

Also corrected the collection.id and collection.description examples to reflect reality.

BGDIINF_SB-1409: Updated spec with correct links examples

---

app/stac_api/models.py

Clean up deprecated comment, added logs, fixed styling, etc.

Some model clean up

---

app/stac_api/models.py
app/stac_api/sample_data/swissMapRaster200/collection.json
app/stac_api/sample_data/swissTLMRegio/collection.json
app/stac_api/serializers.py

* on collection level, stac_extensions is now []
* sample `collection.json` of the two sample collections is corrected accordingly

BGDIINF_SB-1456: remove stac extension from collections

---

spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

Collection and Assets did not had the created and updated fields
The item properties obect did not had the title field.

BGDIINF_SB-1476: Added missing fields in spec: created/updated/title

---

app/stac_api/collection_summaries.py
app/stac_api/models.py
app/tests/test_collections_summaries.py

**The branch name has 1461 instead of 1462, it has been too late at night when working on it obviously. Sorry for that! The commit messages were updated with the correct number, thanks Brice ;-) **
* implemented delete-case for assets in collection's update_summaries()
* added first unit tests for delete-case
* noticed while unit testing that update-case for assets was not complete yet --> implemented/fixed insert and update-cases as well
* exported collection's update_summaries() to separate file

BGDIINF_SB-1462: collection's update_summaries() on asset insert/update/delete

---

app/stac_api/admin.py
app/stac_api/templates/admin/ol_swisstopo.js

Right now no map is being displayed on dev and int
This is a quickfix to display the map from the
official wms.geo.admin.ch (pk1000)

BGDIINF_SB-1488: display a map on dev and int

---

app/tests/test_admin_page.py

Due to the BGDIINF_SB-1500 bug the admin page collection removal with
items test case doesn't work, therefore it is commented out until
BGDIINF_SB-1500 is fixed.

BGDIINF_SB-1477: Added admin page unittests 

---

app/stac_api/apps.py
app/tests/database.py
app/tests/test_generic_api.py

The previous link replaced the next link. Now both link can live
together.
Added unittest case to make sure that both can live together when
needed.

BGDIINF_SB-1502: Fixed pagination bug

---

spec/components/responses.yml
spec/components/schemas.yml
spec/paths.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

* Some clean up in the error schema and examples
* Added ETag and Location headers to Collection
* Corrected Item POST/PUT/PATCH responses to give back the created/updated item
* Corrected the DEL of Asset/Item with the 200 OK instead of 204 No Content
NOTE: The ETag might still requires some changes based on up coming implementation.

BGDIINF_SB-1482: Updated Transactional SPEC

---

spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

Same issue as for the GET Asset SPEC, see  #141

BGDIINF_SB-1482: Fixed Asset SPEC POST/PUT/PATCH

---

app/stac_api/views.py
app/tests/test_assets_endpoint.py

* added asset POST, PUT, PATCH and DELETE
* added unit tests

BGDIINF_SB-1483 asset write endpoints

---

app/stac_api/validators_serializer.py
app/tests/base_test.py

Improved user error message in validator.
Also removed duplicate key in unittest error message (the key is already
part of the path)

BGDIINF_SB-1546: Improved error messages

---

app/stac_api/views.py
app/tests/test_items_endpoint.py

When using the next link from a items datetime query result, the API
returned a 500: "Calling QuerySet.filter() after union() is not supported."
So instead of using union() I use Q(). This is now working (see previous
unittest commit)

BGDIINF_SB-1575: Fixed items datetime query pagination

---

app/stac_api/apps.py
app/stac_api/urls.py
app/stac_api/views.py
app/tests/test_search_endpoint.py
spec/components/parameters.yml
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

- Added a unittestfile
- Copy of view ItemList to SearchList as a base for search endpoint
- Separation of functions used in several views

BGDIINF_SB-1484: Realise the /search endpoint

---

app/stac_api/views.py
app/tests/test_search_endpoint.py
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

BGDIINF_SB-1537: Better POST search examples in spec

---

app/stac_api/management/commands/dummydata.py
app/stac_api/managers.py
app/stac_api/models.py
app/stac_api/views.py
app/tests/test_search_endpoint.py

Putting general filter functions to become methods of a custom QuerySet class

BGDIINF_SB-1484: Own QueryClass for fiter functions

---

app/stac_api/apps.py
app/stac_api/models.py
app/stac_api/validators_serializer.py
app/tests/test_assets_endpoint.py

Added more logs in models and improve error message in asset validation.

BGDIINF_SB-1546: Added debug log when saving/deleting models

---

app/stac_api/collection_spatial_extent.py
app/stac_api/migrations/0001_initial.py
app/tests/sample_data/item_samples.py
app/tests/test_item_to_collection_endpoint.py

Now the update of the bbox of the collections is also practical
when having 10K of items.

BGDIINF_SB-1630: Faster update of aggregated collection bbox

---

spec/components/schemas.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

BGDIINF_SB-1589: Correction in Spec POST / Search

---

app/stac_api/collection_spatial_extent.py
app/stac_api/collection_summaries.py
app/stac_api/collection_temporal_extent.py

* added only() in collection_spatial_extent, collection_temporal_extend and collection_summaries
* in every only() for items, the field collection has to be included, due to the select_related('collection')
in the ItemManager class.

BGDIINF_SB-1569 added only()

---

app/templates/admin/base.html
app/templates/rest_framework/base.html

We also fixed a css bug from PR 1318.

BGDIINF_1439: adding header and footer to REST API page

---

app/stac_api/management/commands/dummy_data.py

Threading in generating dummy data is disabled if the two `--parallel-*` options are 1

don't start threads if parallel is set to 1

---

app/config/settings_prod.py
app/middleware/cors.py
app/tests/test_generic_api.py

this PR adds CORS headers to all responses.

BGDIINF_SB-1663 add CORS headers to all responses

---

spec/base.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

Remove the note about api being not productive yet from the spec.

BGDIINF_SB-1689 remove 'non-productive' note from spec

---

app/middleware/logging.py
app/stac_api/apps.py

adapted middleware/logging.py and stac_api/apps.py to log payload of requests to write endpoints

BGDIINF_SB-1671: added logging of requests and payloads for write endpoints

---

scripts/sql/samples/load_random_data.sql

this script will load random data into
* stac_api_collection
* stac_api_item

add random data loader sql script

---

app/stac_api/admin.py
app/stac_api/models.py
app/stac_api/templates/js/admin/asset_help_search.js
app/stac_api/templates/js/admin/collection_help_search.js
app/stac_api/templates/js/admin/item_help_search.js
app/stac_api/templates/style/hover.css

Issue : We wanted a help text to help users better use the tool within
the admin pages
Fix :
Added help texts to asset and item detail pages for the search.
Added a popup window on hover in the searches of general admin pages
search.
further fixes needed :
Indentation in JS files.

BGDIINF_SB-1578: help text support for search

---

app/middleware/logging.py
app/stac_api/apps.py

The url query params should appear in the logs as well.

add url query to logs

---

Pipfile
Pipfile.lock
app/config/settings_prod.py
app/stac_api/admin.py

using https://github.com/farhan0581/django-admin-autocomplete-filter to allow filtering for items of a specified collection.
This adds a dropdown list with available collection names as well as an autocomplete textfield for the search.

BGDIINF_SB-1646: 1646 admin interface item filtering

---

app/stac_api/models.py
app/stac_api/serializers.py
app/stac_api/validators.py
app/tests/data_factory.py
app/tests/sample_data/asset_samples.py
app/tests/test_admin_page.py
app/tests/test_asset_model.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_summaries.py
app/tests/test_generic_api.py

Still waiting an answer concerning the file extension for application/vnd.mapbox-vector-tile which I set to `*.mvt` based on https://github.com/mapbox/vector-tile-spec/tree/master/2.1#21-file-extension

BGDIINF_SB-1566: Added unittest for asset media type validation

---

app/stac_api/serializers.py
app/stac_api/urls.py
app/tests/test_collections_endpoint.py

The new code make use of django reverse url functionality and improved code reusability

Improved code for auto generated links

---

spec/paths.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/transaction.yml

Plus some small improvements using shorter summary for operations.

BGDIINF_SB-1723: Updated the spec for collection upsert

---

spec/components/schemas.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/transaction.yml

Corrected the transactional examples in STAC spec:
* removed read only properties
* changed id to small letters
* changed image type
* removed non supported properties

BGDIINF_SB-1670: Correct transactional examples in STAC spec

---

app/stac_api/admin.py
app/stac_api/models.py
app/stac_api/validators_view.py
app/stac_api/views.py
app/tests/test_admin_page.py
app/tests/test_assets_endpoint.py

BGDIINF_SB-1747: No more move asset operations

---

app/stac_api/pagination.py
app/stac_api/s3_multipart_upload.py
app/stac_api/serializers.py
app/stac_api/serializers_utils.py
app/stac_api/urls.py
app/stac_api/utils.py
app/stac_api/views.py
app/tests/test_asset_upload_endpoint.py

Aslo splitted the serializers module into two as it became quite big.

BGDIINF_SB-1739: Added asset upload list parts endpoint

---

app/stac_api/admin.py
app/stac_api/views.py
app/tests/test_collections_endpoint.py

Removing the Possibility to rename a collection and adapted the test accordingly

Feature BGDIINF-SB 1745: remove collection renaming function

---

app/stac_api/management/commands/list_asset_uploads.py
app/stac_api/s3_multipart_upload.py
app/stac_api/utils.py

This command won't work correctly with S3 minio server as it doesn't implement the ListMultipartUploads correctly.

BGDIINF_SB-1739: Added management command to list all asset uploads

---

app/stac_api/collection_temporal_extent.py
app/stac_api/models.py
app/tests/test_collection_model.py

* collection's `updated` property is now updated, when a child item/asset of the collection is inserted, updated or deleted.
* corresponding unit tests were added to `test_collection_model.py`

BGDIINF_SB-1753 update collections upstream

---

spec/components/schemas.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/examples.yaml
spec/transaction/paths.yaml
spec/transaction/tags.yaml

Those examples did not relfect a correct sha2-256 multihash.

Changed invalid checksum:multihash examples in SPEC

---

README.md
app/stac_api/admin.py
app/stac_api/models.py

This gives the possibility to list all asset uploads.

BGDIINF_SB-1810: Added admin page for asset upload

---

app/stac_api/templates/admin/ol_swisstopo.html

The favicon link was not correct.

#patch, BGDIINF_SB-1826: Fixed again admin item 500

---

app/stac_api/models.py

added collection, item and asset to the extra
added size of asset file to log msg

added more details to log msg in models.py

---

buildspec.yml

This merge will have to be coordinated with other PRs like the one with the cubernetes definitions

BGDIINF_SB-1839: Docker to ECR

---

app/stac_api/views.py
app/tests/test_admin_page.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py
app/tests/test_items_endpoint.py
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/paths.yaml

Those endpoints are not needed anymore since we have the UPSERT PUT
method.
Addapted also unittests.

BGDIINF_SB-1725, BGDIINF_SB-1726: Removed POST collections/items/assets endpoints

---

spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/paths.yaml

Specified the possible error message on the PUT presigned URL operation in the SPEC.

Added Asset PUT presigned URL error message in SPEC

---

README.md
scripts/multipart_upload_via_api.py
scripts/upsert_asset_via_api.py

* improved error handling in case of no or wrong credentials are provided for multipart-upload script
* added new script for creating a new asset via the API

feature_BGDIINF_SB-2135: improved error handling and added new script

---

app/stac_api/views.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py
spec/Makefile

Order the collection by title instead of its id.
The unittests had to be adapted accordingly

BGDIINF_SB-2196: Order collections by title

---

Pipfile
Pipfile.lock
app/config/logging-cfg-local.yml
app/middleware/logging.py

BGDIINF_SB-2520: Improved logging

---

spec/components/schemas.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

This PR has been opened based on question from a user.

Added precision in spec for title min, max length

---

app/middleware/cache_headers.py

BGDIINF_SB-2704: set custom cache-control headers for some temporary

---

adr/2023_02_27_cache_settings.md

This ADR will be discussed on 27.02.23 at 13:00 on tech talk call.

BGDIINF_SB-2799: ADR Cache settings

---

spec/components/parameters.yaml
spec/components/responses.yaml
spec/components/schemas.yaml
spec/openapi.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/parameters.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

Notes:
- I made the getAssetObject endpoint part of the 'public' api docu, not only the transactional part
- Docu about the `update_interval` parameter is restricted to the transactional part

BGDIINF_SB-2799: added docu about asset object caching behaviour

---

app/stac_api/management/commands/dummy_data.py

This command did not worked, because we were not allowed to delete non empty
collection/item.

Fixed `manage.py dummy data clean` command

---

app/stac_api/views.py
app/tests/test_search_endpoint.py

In the search endpoint an aggregation over the whole queryset was done for
the update interval. This can potentially be very slow as a GET /search return
a queryset with all items in the DB ! Also the aggregation was done even
in a POST /search where we don't need to add Cache-Control header !
Now the cache-control header is only in GET /search geadded and the
update_interval aggregation is also only done for GET request.
The aggregation is done on the paginated queryset, meaning up to maximum of
100 items. We need to set the cache control header for the response of the
request and not based on all matching items.
Has we can see below the performance tests are passing again:
BASE:
```text
environment: alb-int
service-version: ltshb.v1.16.0-beta.10-1-g1d1e5e2
test-version: f34b8db
pods: 3 …
```

BGDIINF_SB-2799: Fixed performance issue with the search endpoint due to update_interval

---

app/stac_api/validators.py
spec/components/schemas.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/tags.yaml

Spec can be tested here : 
- https://sys-data.dev.bgdi.ch/api/stac/static/spec/v0.9/api.html
- https://sys-data.dev.bgdi.ch/api/stac/static/spec/v0.9/apitransactional.html#tag/Asset-Upload-Management

BGDIINF_SB-2835: Improved docu in spec about compression

---

app/stac_api/utils.py
app/tests/test_items_endpoint.py
app/tests/test_items_endpoint_bbox.py

Testing for invalid params for bbox

BGDIINF_SB-2874: invalid bbox params testing

---

Pipfile
Pipfile.lock
README.md
app/stac_api/managers.py
pytest.ini

Added the necessary configuration to be able to run the unit test from within vscode:
See README for more information. Also: https://github.com/geoadmin/service-control/pull/6

Added debugging and testing capabilities for vscode

---

app/config/settings_prod.py
app/stac_api/management/commands/remove_expired_items.py
app/stac_api/validators_view.py
app/stac_api/views.py
app/tests/tests_10/test_assets_endpoint.py
app/tests/tests_10/test_items_endpoint.py
app/tests/tests_10/test_remove_expired_items.py
docker-compose.yml

New management command to delete expired items and their assets.
Remove expired items from result in get & list items/assets endpoints.

PB-848: Delete expired items

---

spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

Add optional href field to request body of create/update asset.

Fix spec asset href

---

app/stac_api/management/commands/update_asset_file_size.py

Change the implementation of the file size update management command so that it uses the s3 backend to determine the file size of an object.
This is needed because the file path can actually differ from the asset name, as is the case with for instance
https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.bahnen-winter/items/bahnen-winter/assets/additional-files_bahnen-winter_2056.zip

PB-1091 Fix file size updater

---

app/stac_api/serializers/item.py
app/tests/tests_09/test_items_endpoint.py
app/tests/tests_10/test_items_endpoint.py
spec/components/schemas.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

This way we can remove them with a PATCH.

PB-1492: Made all optional item properties nullable in PATCH

---

app/middleware/api_gateway_middleware.py

No need for two if's when one suffices.

Simplify logic.

---

Pipfile
Pipfile.lock

There is no specific indication it will resolve our issue but the problem is related to gevent/urllib3 interaction so we might just as well try. We are already using the latest urllib3 release.

Upgrade gevent.

---

Pipfile
Pipfile.lock
app/wsgi.py

In https://github.com/geoadmin/service-stac/pull/560 we worked around a bug in gevent. This was fixed in gevent 25.4.1. In this PR we upgrade to that version of gevent and remove our workaround.

Upgrade gevent and remove our custom bug workaround.

---

.env.default
README.md
app/config/settings_dev.py
app/stac_api/utils.py
app/tests/test_multiple_bucket_setup.py

Move away from the regexes for configuring the managed bucket collections

PB-1847 Switch the managed patterns to prefixes
