geoadmin/service-stac

Dockerfile

Django project requires some apt package dependencies in order to run.
See https://docs.djangoproject.com/en/3.1/ref/contrib/gis/install/geolibs/

Added missing dependencies in docker file

---

Makefile
docker-compose.yml
project/project/settings.py

Made the `DEBUG` and `ALLOWED_HOSTS` flags configurable via environment variables. 
The `DEBUG` flag is per default to `False` and set to `True` in the makefile for local development.
The `ALLOWED_HOSTS` will be then set to the DEV, INT or PROD host name by k8s.
Also improved the makefile with usefull targets for local development.

DEBUG and ALLOWED_HOSTS configuration + minor makefile improvement

---

README.md

The STAC API link in the summary refered to the STAC API 1.0beta instead of the 0.9.0

Updated doc summary and added links

---

.pylintrc
.style.yapf
project/app/urls.py
project/app/views.py
project/project/settings.py
tests/unit/test_landing_page.py

The `links` attribute was missing in the landing page. The description has
also been updated as required by management.
Also renamed the landing page function called `index` to `landing_page`
which is the name of the page as defined in the ticket and spec.

BGDIINF_SB-1317: corrected the landing page

---

Makefile

It seems that the `manage.py migrate` command will be often used,
therefore add it as makefile target to simplify its uses.
Also added the `manage.py check` command to the lint target. This
command is kind of a django linting command as it does some static code
checking (see https://docs.djangoproject.com/en/3.1/ref/checks/). To
start with the WARNING level but this could change in the future as we
gain experience with django.

Added django migrate and django check in makefile

---

project/config/logging-cfg-dev.yml
project/config/logging-cfg-local.yml
project/config/logging-cfg-prod.yml

UTC time format is a better choice for the ELK (Elastic Logstash
Kibana).
See comment in https://jira.swisstopo.ch/browse/BGDIINF_SB-1260

BGDIINF_SB-1260: Use UTC time format in logging

---

project/stac_api/models.py

* added one missing `max_length` to a CharField (missed one field so far, sorry)
* added a list() to some ArrayField's default values, in order to hopefully fix this error:
> ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
> --
> 1004 | HINT: Use a callable instead, e.g., use `list` instead of `[]`.

added 1 missing max_length / added list() to ArrayField's defaults

---

project/stac_api/models.py

added function that returns values of a dictionary with default values for stac extensions for ArrayFields.
This way the following issue is hopefully solved:
> ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
> --
> 1004 | HINT: Use a callable instead, e.g., use `list` instead of `[]`.

solved issues with default values for ArrayFields

---

.style.yapf

Added two configuration to avoid issues with complex dictionary styling,
see https://github.com/geoadmin/doc-guidelines/pull/55

Updated yapf config to match guidelines

---

README.md
app/config/logging-cfg-dev.yml
app/config/logging-cfg-local.yml
app/config/logging-cfg-prod.yml
app/stac_api/views.py
requirements.txt

Add the Django HttpRequest info to the log ouptut of the landing page.
This requires the new upcoming logging-utilities 1.1.0, currently it uses the alpha version which will be updated as soon the PR https://github.com/geoadmin/lib-py-logging-utilities/pull/3 is accepted and merged.

BGDIINF_SB-1291: Added django request info to log output

---

Dockerfile
Makefile
app/config/settings_prod.py
app/config/urls.py
app/wsgi.py
requirements.txt

WhiteNoise is used for production and development as server for static assets. Django itself is not appropriate to use for serving static asset on production. Gunicorn cannot directly serve static files as well.
Some good practice is to use NGINX to serve django static files which is also recommended to use as Reverse Proxy for gunicorn. However in our setup we don't uses nginx because we have a CDN on top of our architecture (CloudFront) which solves the problems that nginx is solving for gunicorn.
Therefore in order to avoid adding nginx to our container to serve static files, I used Whitenoise. Whitenoise is good solution when using with a CDN and for low traffic static files.
See also https://medium.com/technolingo/fastest-static-files-served-django-compressor-whitenoise-aws-cloudfront …

BGDIINF_SB-1343: serve static assets using WhiteNoise

---

.env.default
README.md
app/config/settings_prod.py
app/tests/runner.py

Now you can completely disable logging via an simple boolean environment
variable `DISABLE_LOGGING`. This is usefull espacialy when working with
the django shell.
Also fixed the `TEST_ENABLE_LOGGING` which true when defined but didnot
checked the value correctly.
Updated the documentation accordingly and also removed old mention to
`pip` in docu while we are now using `pipenv`

Improved logging configuration for development

---

Dockerfile

The minimal image we're currently building doesn't offer tools for debugging networking issues in the container running on k8s. 
A slightly bigger image is built with this PR including some of the popular tools for debugging networking issues. Can be removed at a later stage once issue is found.

adding some debug packages to the image

---

.env.default
app/config/settings_dev.py
app/config/settings_prod.py
app/config/urls.py
app/stac_api/apps.py
app/stac_api/views.py
app/tests/test_generic_api.py

Now all Rest API HTTP error message follow the API spec and are json  format:
`{"code": int, "description": str}`
Exception are 404 NOT FOUND when given an invalid URL, e.g. http://data.geoadmin.ch/unknown-url => gives an HTML 404 response.

BGDIINF_SB-1395: Changed HTTP error message to json format

---

app/tests/test_item_to_collection_propagation.py

Here tests have been added to test, if the propagation of the geometries
from item to the collection bbox work as expected.

BGDIINF_SB-1427: Testing if the propagation to the collection bbox works

---

app/stac_api/admin.py

Now collection and item links are inlined in the admin page like the
providers. This way we have a consistent admin interface.

Moved collection and item links to be inlined in admin page

---

Dockerfile
app/config/settings_dev.py
app/config/settings_prod.py

The secret key is now read from environment variable. The old key is kept only for local development purpose and has been moved out fo settings_prod.py.
This PR is required for https://github.com/geoadmin/infra-kubernetes/pull/29

BGDIINF_SB-1401: Read the SECRET_KEY from env variable

---

app/config/settings_prod.py
app/stac_api/serializers.py
app/stac_api/urls.py
app/stac_api/views.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_collections_model.py
app/tests/test_generic_api.py
app/tests/test_items_endpoint.py
app/tests/test_landing_page.py
app/tests/test_sampledata.py

The links to the API documentation (html and yaml) had a double // in
front of `static` which broke the link.
To fix it I removed the trailing slash in API_BASE settings, because it
make the code more explicit and is less prone to errors as it happened
with the static links of the api doc.

BGDIINF_SB-1402: Fixed link to api doc

---

Dockerfile
Makefile
app/config/settings_dev.py
app/config/settings_prod.py
buildspec.yml
docker-compose.yml

The docker production image could not be started with the DEBUG flag set
to true. This was due to the fact that the DEBUG=True required some
django app that were only configured in the settings_dev.py and not in
prod settings.
Now in the prod image the DEBUG flag is forced to false to avoid issue
when the flag is externally set (e.g. deploying a production image on
dev staging). Anyway we should never deploy an image on production with
django DEBUG enabled.
Also renamed the docker image target test to debug as this target is not
olny used for testing in the CI but also used on the k8s dev staging.

BGDIINF_SB-1401: Fixed DEBUG=True prod image and renamed docker target test

---

Dockerfile
Makefile
buildspec.yml

I added some metadata to a docker image:
- git commit hash
- git branch
- git dirty => '' or the output of "git status --porcelain" if the repo is dirty
- author
- target
These metadata can be easily seen on dockerhub, see https://hub.docker.com/layers/swisstopo/service-stac/ltshb.latest-dev/images/sha256-e9ca799a1a8d1621f37e203b809cf8f4fbb9d643c84b2abde9f9231f96ded899?context=explore as example and seek for `LABEL`
You can also check the metadata as follow:
```
docker image inspect --format='{{json .Config.Labels}}' swisstopo/service-stac:ltshb.latest-dev | jq
{
"author": "ltshb",
"git.branch": "feature_docker_image_metadata",
"git.dirty": "",
"git.hash": "47545796f9418ccdb9769d87c6e691248992b4d1",
"target": "debug"
}
```
Or from running container with:
```
docker ps --format="table …
```

Add metadata to docker image

---

spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

Our current implementation doesn't supports open interval. Because this
is not required and not supported, simply remove it from spec.

BGDIINF_SB-1429: Updated the collection temporal extent spec

---

app/stac_api/serializers.py
app/tests/test_items_endpoint.py
app/tests/test_serializer.py

Now the Item serializer is complete with deserialization and with a good
test coverage.
Move the item properties "created" and "updated"  into "properties:
{created: , updated: }" to match the spec.

 BGDIINF_SB-1367: Finalize item deserialization and moved item created/updated props

---

spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

These attributes are currently not implemented. They might be required
to implement the pagination of the search endpoint but this still needs
to be verified (aka the django rest framework cursor pagination might
not need it)

BGDIINF_SB-1469: Commented out link merge, body, headers, method and length attribute

---

spec/components/parameters.yml
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

As this query is not implemented yet, it has been removed from the spec.
Removed means in this case, that it has been hidden as a comment #

BGDIINF_SB-1454: Remove assetQuery from doc

---

app/stac_api/temporal_extent.py

replaced `item.__class__` with `type(item)` in `temporal_extent.py` as it is a "best practice" and in order to be consistent with `collection_summaries.py` from https://github.com/geoadmin/service-stac/pull/117

replaced item.__class__ with type(item) in temporal_extent.py

---

.github/workflows/main.yml
Dockerfile
Makefile
README.md
app/config/admin.py
app/config/apps.py
app/config/settings_prod.py
app/config/version.py
app/middleware/settings_context_processor.py
app/templates/admin/base.html
app/templates/rest_framework/base.html
buildspec.yml

This PR is implementing versioning guideline as described in https://github.com/geoadmin/doc-guidelines/pull/65 for service_stac.
It uses a github action (executed on push to `develop` and `master` only) to automatically tag pushes to `develop` with `vMAJOR.MINOR.PATCH-beta.Y` and pushes to `master` with `vMAJOR.MINOR.PATH`. These tags are used during the build step to overwrite a `version.py` file which itself is used in templates to display the currently deployed version in the admin pages and API landing page.

BGDIINF_SB-1497 adding version information

---

app/config/logging-cfg-local.yml
app/config/settings_prod.py
app/tests/test_cf_forwarded_proto.py

Django doesn't correctly determine if the original request was made using SSL with our Stack. Therefore we need to adapt the settings value SECURE_PROXY_SSL_HEADER

BGDIINF_SB-1503 changing setting for SECURE_PROXY_SSL_HEADER

---

buildspec.yml

https://github.com/geoadmin/service-stac/pull/124 introduced a bug that was only visible after the merge to `develop`. This PR should fix it.

BGDIINF_SB-1497 fixing docker image tagging for '*-dev' images

---

app/stac_api/serializers.py
app/tests/test_collections_endpoint.py

When the provider is None, this attribute will not to be shown
in the collection endpoint any more.

BGDIINF_SB-1515: Collection Endpoint: Do not show empty provider

---

app/config/settings_prod.py
app/stac_api/urls.py
app/tests/test_collections_endpoint.py
app/tests/test_get_token_endpoint.py
app/tests/test_items_endpoint.py

* added token, basic and session authentication
* set `DjangoModelPermissionsOrAnonReadOnly` as default (non-logged in, anonymous users have read-only access, logged-in users can take actions according to their individual permissions)
* added POST endpoint for users to request a token based on their username and password
(e.g. as follows: `curl -d "username=testuser&password=test12345" http://127.0.0.1:8000/api-token-auth/`)
* added unit tests for authorized POSTs as well as unauthorized POSTs or requets with wrong credentials
The POST/PUT endpoints for collections as well as a lot of the unit tests and test data for the collections_endpoint were borrowed from https://github.com/geoadmin/service-stac/pull/132, thanks @rebert :smiley:

BGDIINF_SB-1491: authentication

---

spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

With the SPEC rework for Transactional, a copy paste issue in the Asset
Spec has been introduced. The Asset returned the same response as the
Item.

BGDIINF_SB-1482: Fixed copy paste bug in Asset spec

---

app/stac_api/models.py
app/tests/test_item_model.py
app/tests/test_serializer.py

* now end_date cannot be before start_date in items datetime ranges
* added unit tests for item model and item serializer
* in case the item's (start_, end_)datetime property is not an instance of datetime, it is now checked, if it is a valid datetime string.

BGDIINF_SB-1510: fixed invalid datetime range | added unit tests

---

app/stac_api/apps.py
app/tests/base_test.py
app/tests/test_generic_api.py
spec/components/responses.yml
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml

Some django errors are encapsulated in object or list in order to
provide a good and detail error descrition in an organized structure. In
order not to loose this structure and organization we allow in the spec
to have the 'description' error field not only be string, but also array
and object.

Corrected the SPEC and unit tests for the error description type

---

Pipfile
Pipfile.lock

requests package has been installed because of moto, but this introduced
a warning. To remove the warning requests has been manually installed
with
pipenv install requests~=2.25.0 --dev
This automatically moved the moto declaration in Pipfile and removed the
warning below:
```
lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Ignoring importlib-resources: markers 'python_version != "3.4" and python_version < "3.7"' don't match your environment
```

BGDIINF_SB-1533: Fixed requests dependency warning

---

Makefile
Pipfile
Pipfile.lock

Testing took more than 200s, now with using parallel testing it is reduced to ~75s.
The number of parallel test has been set to a maximum value for
performance improving (adding more doesn't reduce the execution time).
**IMPORTANT NOTE:** For subTest the error message is not useful when running in parallel, which means that if a subTest fails we need to manually restart the tests in sequence to know what went wrong. With parallel testing and subTest we only know which test failed but don't have the error message. This is only for subTest not for regular test.

Run test in parallel to speed up testing

---

spec/transaction/transaction.yml

There's no `overwrites` folder anymore, so the deleted comment was obsolete

deleted two lines of obsolete comments in transaction.yml

---

app/stac_api/models.py
app/stac_api/serializers.py
app/stac_api/validators.py
app/tests/test_generic_api.py
app/tests/test_item_model.py

The item properties datetimes were validated twice in a row. This was
unecessary and due to a wrong uses of the django/rest_framework in
unittest. Creating an object with
ModelClass.objects.create(**validated_data) should
only be done with validated data, like for example in the serializer.
This method doesn't do any validation. If we don't have validated data,
then we need to use ModelClass(**unvalidated_data).full_clean().save()
So the item model unittest has been corrected in order to remove the
self.clean() in the item.save() method. This introduce a sligthly
performance improvement, but more important it makes the code cleaner.

BGDIINF_SB-1534: avoid duplicate validation in items

---

app/stac_api/collection_temporal_extent.py
app/stac_api/models.py
app/stac_api/utils.py
app/stac_api/validators_serializer.py
app/stac_api/views_mixins.py
app/tests/data_factory.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_items_endpoint.py
app/tests/test_serializer.py
app/tests/utils.py

The serializer hide_fields did not work for the asset put/patch
endpoints because the parameter was not passed in the view mixins. This
has been fixed.
In data_factory, allow to use extra attribute with the
required_only=True. This way we can retrieve the minimal attributes plus
an extra.
Completed the asset endpoint unittest to test the asset management. What
still missing is testing the asset managment on S3 (uploading/moving/deleting
asset) because S3 is currently mocked in unittest.

BGDIINF_SB-1568: Fixed serializer hide_fields and added asset mgmt tests

---

app/config/logging-cfg-prod.yml

logging settings changed for prod: DEBUG logs from app should be printed as well, WARNING for all other loggers
Note: this is done as a `hotfix` (branched off `master`) to check if hotfix versioning (patch position in semver) is working correctly. A hotfix branch has to be merged back in both, `develop` and `master`

#patch prod logging settings

---

app/stac_api/views.py
app/tests/test_items_endpoint.py

This fix treats a bbox pseudo point as a point and a
regular bbox as a polygone for intersects with items

Bugfix BGDIINF_SB-1412: A pseudo point in the bbox should be allowed

---

app/config/logging-cfg-local.yml
app/config/settings_dev.py
app/stac_api/admin.py
app/stac_api/management/commands/dummydata.py
app/stac_api/models.py
app/stac_api/validators.py
app/stac_api/views.py

make use of `prefetch_related` in list and detail views to reduce the number of queries that are made to fetch related objects
added a mgmt command to generate diverse (i.e. with all expected values) dummy data for performance testing

BGDIINF_SB-1564 perf test dummy data, prefetch_related

---

app/stac_api/serializers.py
app/stac_api/urls.py
app/stac_api/views.py
app/tests/base_test.py
app/tests/data_factory.py
app/tests/test_assets_endpoint.py
app/tests/test_items_endpoint.py
app/tests/test_sampledata.py
app/tests/test_serializer.py
spec/components/schemas.yml
spec/static/openapi.yaml
spec/static/openapitransactional.yaml
spec/transaction/transaction.yml

Now the Asset views have the same schema as the items and collections.
This adds the links attribute to the asset view.
Note the the assets that are nested in Item view, are not touched.
Also fixed a bug in the PATCH item answer were the 'type' attribute was missing.
This PR code is currently deployed on DEV and can be tested: https://service-stac.dev.bgdi.ch/api/stac/v0.9/collections/ch.swisstopo.pixelkarte-farbe-pk200.noscale/items/smr200-200-2-2016/assets

BGDIINF_SB-1537: Harmonized Assets view with Item and Collections

---

app/stac_api/collection_summaries.py
app/stac_api/collection_temporal_extent.py
app/tests/test_collections_model.py

* made use of QuerySet caching in collection_temporal_extent.py
* optimized performance by using exists() insteadof bool() in collection_summaries.py
* optimized performance by re-using already evaluated quersets in collection_temporal_extent.py
(The readability of code has suffered a bit under this, but I documented and commented, so I hope, it still is OK)

Feature BGDIINF_SB-1545 query set caching

---

Makefile
README.md
app/config/settings_prod.py
app/middleware/cache_headers.py
app/stac_api/admin.py
app/stac_api/urls.py
app/stac_api/views.py
app/tests/test_generic_api.py

Adds the following headers to the django views:
- `Expires: DATE_600_SEC_AHEAD_FROM_NOW`
- `Cache-control: max-age=600, public`
- `Vary: Accept, Cookie` (Added automatically by Django)
The max-age and expire is configurable via `HTTP_CACHE_SECONDS`
For the static files the following headers are added (added automatically by Whitenoise):
- `cache-control: max-age=3600, public, immutable`
- `Expires: DATE_600_SEC_AHEAD_FROM_NOW`
The max-age and expire is configurable via `HTTP_STATIC_CACHE_SECONDS`
_NOTES:_
- it would be useful to have caching enabled in /search POST endpoint, however CloudFront apparently doesn't supports caching on POST requests.
- I did not use the Django CacheMiddleware, because it first install a default cache ([Local-memory …

 BGDIINF_SB-1571: Sets appropriate cache headers in GET and HEAD responses

---

app/stac_api/managers.py

when checking all the .filter(), Q(), et al. expressions for BGDIINF_SB-1541, I came along this Q()
and thought, it might be `properties_start_datetime` instead of `properties_end_datetime` here.
There were no unit tests complaining after this change. Probably the existing tests need to be adapted or new ones added? I'll create a ticket for that, what do you think @rebert ?

fixed small issue in _filter_by_datetime_range

---

README.md

Issue : The current README wasn't clear enough about the standard way of using databases in local development (through containers).
Fix : 
- Rewrote the README to be more explicit about the database setup and the standard way of doing it.
- Moved the 'setup app' section to 'Creating the local environment' and placing the section before the database section, that way, the steps to take to set up service stac locally are in order
- Added a mention to 'make setup' at the end of 'Creating the local environment', as this commands goes a bit further than pipenv install, and described quickly what it entails.

BGDIINF_SB-1548: README rewrite on project setup

---

app/config/settings_prod.py
app/middleware/cache_headers.py
app/stac_api/serializers.py
app/tests/test_landing_page.py
app/tests/test_serializer.py

Static files already have the cache header therefore do not overwrite
them.

BGDIINF_SB-1571: Do not use the cache middleware for static files

---

README.md
app/stac_api/collection_spatial_extent.py
app/stac_api/collection_summaries.py
app/stac_api/collection_temporal_extent.py
app/stac_api/models.py
docker-compose-ci.yml

This improves the logging of the collection updates (extent and summaries).
To simplify the logging and improve the filter possibilities, I moved all code related to the collection update in separate modules. This give the possibility for example on ELK to filter all the logs related to the collection update summaries, or to the update spatial extent, ...
In the last commits I refactored the collection update in mixins, this is not really needed and could be reverted if you don't like it ? Note that some logs are then still in the models.py module.
@rebert @hansmannj  @boecklic for the review you might want to review commit by commit, otherwise the diff is just huge due to reorganisation. The last 3 commits is just the refactoring in mixin.

BGDIINF_SB-1546: Improvements of collections update logs

---

Makefile
Pipfile
Pipfile.lock
app/config/settings_prod.py
app/config/urls.py

This PR adds django-prometheus and exposes the default app metrics defined in that package. This is intended as a first iteration to test integration of service and prometheus, get to know prometheus and it's possibilities. These findings will help to tailor exposed app metrics to our needs.

BGDIINF_SB-1612 default prometheus-consumable app metrics

---

app/stac_api/signals.py

When deleting a collection from the admin page, the update extent and
summaries was triggered for each asset and items that was also deleted.
When deleting from the admin page, the model's delete() method are not
called, but the `pre_delete` signal is sent. With this signal we are
deleting asset on S3 using the File delete() method. This method
triggered and Asset update which was triggering a collection summaries
update and an item update which triggered a collection extent update.
Because we are deleting an asset (file and metadata) it doesn't make
sense to save the metadata object.
This improves massevely performance for deletion from admin page
(deletion of a collection with several thousand items did not work
before due to timesout)

Do not update the collection extent and summaries on collection delete.

---

app/stac_api/models.py
app/stac_api/signals.py
app/tests/test_admin_page.py

In order to avoid any bad surprise short for the go live on march and
due the performance issue when changing item geometry the asset
management on S3 is temporarly commented out. This needs to be somehow
reintroduce after the go live within BGDIINF_SB-1625

BGDIINF_SB-1624: Comment ou temporarly asset management

---

app/tests/test_search_endpoint.py

Issue : Tests on the search endpoint lacked a testcase to check if exact
datetimes queries worked.
Fix : Created Two tests
One checks if an exact datetime query works as intended
One checks if an exact datetime query with a non-date string returns a
400 error as should be the case.

BGDIINF_SB-1617: adding exact datetime search queries tests

---

README.md
app/config/settings_prod.py
app/config/urls.py

The localhost IP / IP of the Pod must be in `ALLOWED_HOSTS` to allow request from local without host header. This is the case e.g. for prometheus (in principle it's the same issue with the health check)

adding local / Pod IP to ALLOWED_HOSTS

---

app/tests/base_test.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py

Unittest improvements:
- Make sure that in case of an expected HTTP 400, the error message is the one we expect. HTTP 400 have many different reason that's why we should test the reason as well in unittest
- Make sure also that STAC required read only fields are present in unittest.

BGDIINF_SB-1626: make sure that the required read only fields are checked in unittest

---

LICENSE.md

The code is published open source and must contain a swisstopo-approved license file.

Adding BSD-3-clause license file

---

app/stac_api/views.py
app/tests/test_assets_endpoint.py
app/tests/test_items_endpoint.py

Issue : When trying to access the items from a non existing collection,
or when trying to access the assets from one non existing item, the
application would return a 200 status with an empty list of items or
assets.
Fix : using the get_object_or_404() method allows consistent comportment
with other endpoints which returned a correct 404 not found status.

ISSUE BGDIINF_SB_1631: wrong status on items and assets queries

---

app/stac_api/managers.py
app/stac_api/validators_serializer.py
app/tests/test_search_endpoint.py

BGDIINF_SB-1659:
Filtering for `updated` or `created` dates did not work both in GET and POST requests on the search endpoint.
It yielded an error message:
FieldError "Cannot resolve keyword 'properties_updated' into field" 
Internally the query appended the text 'properties_' before the 'updated' or 'created'. Hence `filter_by_query()` in `managers.py` was adapted.
Also new unit tests were added that test POST and GET requests filtering for 'updated' and 'created'.
BGDIINF_SB-1657:
Incorrectly spelled or arbitrary query parameters were accepted and did not yield error messages currently.
So the allowed query parameters were limited to `bbox, collections, cursor, datetime, ids, intersects, limit and query` and validated. Any other query parameter or incorrectly spelled query parameters …

BGDIINF_SB-1659 bugfix in search endpoint (POST and GET)

---

app/stac_api/validators_serializer.py
app/tests/test_search_endpoint.py
spec/components/parameters.yml
spec/components/schemas.yml
spec/paths.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

This PR contains the following changes:
- remove `datetime` from queryable fields in GET and POST /search (it's redundant with the `datetime` query parameter)
- spec: remove `query` parameter in GET /search
- spec: cleanup in GET/POST /search

BGDIINF_SB-1660 remove datetime from queriable fields

---

app/config/settings_prod.py

The api/stac/static/spec/v0.9/openapi.yaml static file was served with
the wrong content-type, it was application/octet-stream instead of application/vnd.oai.openapi+yaml;version=3.0

BGDIINF_SB-1643: Fixed wrong mime type for the openapi.yaml file

---

app/config/logging-cfg-local.yml
app/config/settings_dev.py
app/stac_api/management/commands/profile_cursor_paginator.py
app/stac_api/management/commands/profile_item_serializer.py
app/stac_api/profiling.py

Added 2 django command line for profiling `ItemSerializer.data` and the the `paginator.paginate_queryset(qs, request)` method. Also added a decorator to profile any method. Profiling should only be used for debugging/testing as it adds a lot of overhead.

BGDIINF_SB-1638: Profiling tool

---

app/stac_api/admin.py
app/stac_api/models.py

The asset admin page for create/update an asset could not be displayed
when the DB contained a lot of Items (several hundred of thousand). This
was due to the fact that the view was trying to load all items for the
select box.
Now this issue has been solved by using an auto_complete_fields.
Other than that some other improvements have been done:
- Moved the AssetAdmin at the end of the file to have a consistent class
order
- Added collection and item in the list view
- Allow the search of wholeword using ""
- Organized the asset fields in fieldset
- Displayed the collection name in the asset view (Currently not dynamically updated when the item is changed, for this a save and refresh is unfortunately needed)
Here below some printscreen of the improvement:

BGDIINF_SB-1664: Fixes and improvement of the admin Asset page

---

app/stac_api/serializers.py
app/stac_api/utils.py
app/stac_api/validators.py
app/stac_api/validators_serializer.py
app/tests/test_assets_endpoint.py

Asset href has been already set as read-only, but there were still some
code for href validation that was not anymore in use. This code as been
removed to avoid missunderstanding of the use of AWS_S3_CUSTOM_DOMAIN
Also improved an error message for POST/PUT Asset

BGDIINF_SB-1669: Removed un-necessary validation for asset href

---

app/stac_api/collection_summaries.py
app/tests/test_collections_summaries.py

When deleting an Asset that had no eo:gsd or proj:epsg or
geoadmin:variant (value as None) in a collection with non empty
summaries, a `ValueError("list.remove: x not in list")`. Same for
updating an Asset without eo:gsd or proj:epsg or
geoadmin:variant (value as None) with a value.

BGDIINF_SB-1667: Fixed asset update/deletion crash

---

app/stac_api/views.py

Added a `.prefetch_related('assets', 'links')` to the queryset in the SearchList's get_queryset(). With this, the items endpoint and the search endpoint (POST and GET) perform similarly well

BGDIINF_SB-1684 fixed slow search endpoint

---

app/config/logging-cfg-local.yml
app/middleware/logging.py

The logging middleware message was not very usefull. It did not helped
at all on local developement because we don't use the json format with
the request dictionary and on Kibana the message 'request' did not
helped neither unless we activate the whole request object.

Improved logging

---

app/config/settings_prod.py
app/middleware/exception.py
app/middleware/logging.py
app/stac_api/apps.py

On production build with the DEBUG=False the exception where not logged
because the rest framework custom exception handler in apps.py did
caught all exceptions and returned a proper 500 message (JSON or HTML
depending on Accept header or format query). Due to this the logging exception middleware was not called.
So now we logs the exception in the custom exception handler instead of
in the exception middleware. This means that for all exceptions on the
API endpoints we will have a log message from logger="stac_api.app" with
level CRITICAL and with exc_info=True. 
On the other hand all exceptions happening from
the admin interface endpoints, we will have a log from
logger="django.server" of level ERROR with exc_info=True. This is due to the fact that for those endpoints the rest framework …

BGDIINF_SB-1681: Log exception also on production build

---

app/tests/data_factory.py

The data factory was not very intuitive with the `create_asset_file`
option. So now even if `create_asset_file` and `db_create` are true then
automatically correct the `create_asset_file` instead of given an error.
This makes the usage of the interface more intuitive.

Improved the data factory for unittest

---

app/stac_api/validators_serializer.py
spec/components/schemas.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

* removed the example for `datetime` in query on POST search endpoint
* added examples for `created` and `updated`
* replaced `queriabel` with `queriable` everywhere, to have one consistent word for it everywhere

BGDIINF_SB-1716 query examples in spec

---

app/config/settings_prod.py
app/stac_api/apps.py
app/stac_api/pagination.py
app/stac_api/utils.py
app/stac_api/validators_serializer.py
app/stac_api/views.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py
app/tests/test_search_endpoint.py
spec/components/schemas.yml
spec/paths.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

The `POST /search` did not worked as defined in the spec. The original body with the DB query needs to be passed to the next request. 
To be consistent the spec changed as follow:
`GET /search`:
- DB query in URL query
- limit and cursor for pagination are part of the URL query and are set to the link['href']
`POST /search`:
- DB query is in the POST body/payload as JSON
- limit and cursor for pagination are also in the POST body/payload and only accepted there (ignored if passed in the URL queryparam)
Test link: https://service-stac.dev.bgdi.ch/api/stac/v0.9/search
API Spec test link: https://service-stac.dev.bgdi.ch/api/stac/static/spec/v0.9/api.html
The last commit also fixed a missleading CRITICA log in unittest:
CRITICAL - stac_api.apps: KeyError('collection_name') ...
This message …

BGDIINF_SB-1711: Fixed the POST /search pagination

---

app/config/settings_prod.py
app/stac_api/views.py

This view has currently a bug in the /search endpoint, where the POST
form is wrong, it is using the POST form of the /items view. This is due
to the fact that we reuse the ItemSerializer for the /search view.
Because the browsable view doesn't bring much advantages and because we
know that DRF has a performance issue and that we might have migrate the
views in other serializer framework, we decided to simply remove it for
now as it not yet very known to the customer.

BGDIINF_SB-1715: Removed the Browsable API view

---

.pylintrc
Pipfile
Pipfile.lock
app/config/settings_prod.py
app/stac_api/collection_spatial_extent.py
app/stac_api/management/commands/profile_cursor_paginator.py
app/stac_api/managers.py
app/stac_api/pagination.py
app/stac_api/utils.py
app/stac_api/validators.py
app/stac_api/validators_serializer.py
app/tests/data_factory.py
app/tests/sample_data/collection_samples.py
app/tests/sample_data/item_samples.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py
app/tests/test_items_endpoint.py
app/tests/test_serializer.py
app/wsgi.py

In PR #249, django has been updated and it triggered a lots of no-member
pylint errors when referencing django models. This can be solved by
updating pylint to a version >= 2.6.
The update of 2.6 added a new raise-missing-from check which produced some
errors in our current code. As this check is very usefull, see also
https://stefan.sofa-rockers.org/2020/10/28/raise-from/ I fixed these
errors properly. Note I used `from None` for the ValidationError as
these ones are caught and translated into HTTP 400 errors, they don't
have any backtrace.
The current pylint version 2.7.0-2.7.2 have fixed an issue with the
similarities check, where the check was not done at all when runnings
pylint --jobs=2+, which we do. This showed several duplicate-code issue,
some of them where very relevant, like …

Updated pylint and fixed duplicate-code, raise-missing-from

---

app/config/urls.py
app/stac_api/serializers.py
app/stac_api/validators_serializer.py
app/stac_api/views.py
app/stac_api/views_mixins.py
app/stac_api/views_test.py
app/tests/base_test.py
app/tests/test_collections_endpoint.py
app/tests/test_generic_api.py
app/tests/utils.py

We also make use of the DB atomic transaction to do proper DB rollback
in case of errors.
The get_object() of the views have been removed in order to use the
default implementation using the lookup_field.
Also made all endpoints atomic to assure proper db rollback in case of
error.

BGDIINF_SB-1723: Collection upsert

---

app/stac_api/serializers.py
app/tests/test_assets_endpoint.py

These checks were removed in order to prepare for the new asset
management with presigned url were we first need to create the asset
metadata before uploading the asset file. See BGDIINF_SB-1739.

BGDIINF_SB-1625: Removed asset file verification during POST/PUT/PATCH asset

---

app/stac_api/admin.py

Added autocomplete search fields and dropdown list filters for filtering assets for their collection and/or items.
Following behaviour is implemented:
If a collection is defined in the `filter by collection name` filter, only those items will appear
in the dropdown list of the `filter by item name` filter, that are in the currently selected collection.
ItemAdmin's `get_search_results()` was overriden with a few "hacky" lines for this.
Otherwise, all items would appear in the list, which does not make sense.
Note: The responsiveness after clicking on those filters could be better. Its a bit slow when there are many items or collections. Probably will improve this soon. The performance problem is due to the large number of assets, items and collections and was already a problem before the …

BGDIINF_SB-1647 filter assets for their collection and/or item

---

spec/Makefile
spec/components/headers.yml
spec/components/responses.yml
spec/components/schemas.yml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/transaction.yml

Added asset upload in spec.
Also did some corrections:
- Removed wrong openapi response in PATCH asset
- Moved SPEC generic response and schemas
- Removed the checksum:multihash from write Assets requests + clean ups
- Reorganized the requests by adding two new tags
- Moved the ETag definition from schemas to headers
- Made the collection links optional in write request
I suggest to do the review commit by commit, this will be easier to understands the changes. See also commit messages.

BGDIINF_SB-1739, BGDIINF_SB-1764: SPEC corrections and added asset upload in SPEC

---

app/stac_api/admin.py
app/stac_api/validators_view.py
app/stac_api/views.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_items_endpoint.py

Also improved the Asset admin page. In this one the read only item field
still had the help text for the field search functionality which don't
make sense for read only field. To avoid this simply changed the logic,
adding extra read only fields that are only displayed in the change view
and the write item field is only display in the add view.
Also improved the logging in case off renaming.

BGDIINF_SB-1746: Removed the Item renaming functionality

---

app/stac_api/admin.py

The item geometry field was missing in the admin page. This was due to
the ItemAdmin.get_fieldsets() method which removed the geometry from the
first fieldset.
Now the geometry field has its own fieldset which is also a preparation
for further improvement in geometry field (see BGDIINF_SB-1650)

BGDIINF_SB-1827: Readded item geometry field in admin page

---

app/stac_api/admin.py
app/stac_api/templates/admin/ol_swisstopo.html

The item geometry field was missing in the admin page. This was due to
the ItemAdmin.get_fieldsets() method which removed the geometry from the
first fieldset.
Now the geometry field has its own fieldset which is also a preparation
for further improvement in geometry field (see BGDIINF_SB-1650)

#patch, BGDIINF_SB-1826, BGDIINF_SB-1827: Hotfix Item Admin page - v1.4.1

---

app/middleware/logging.py
app/tests/test_admin_page.py

Currently uploading assets files, which are larger than the default 2.5 MB, which is the default for `DATA_UPLOAD_MAX_MEMORY_SIZE`  fails when using the admin GUI.
The `RequestDataTooBig` exception was raised, when the middleware logging tried to access the `request.body` and hence Djangos `request.py` evaluated the `content_length` against the `DATA_UPLOAD_MAX_MEMORY_SIZE`.
This is now fixed by NOT adding the first 200 characters of the request.body in the middleware logging in case the request.path starts with /api/stac/admin (thanks @ltshb ;-)).
In addition a minor change in `test_admin_page.py`'s `_create_asset()` was done in order to have a more consistent file naming.
Once this PR is merged, I'll deploy the changes toDEV and test to upload a large asset file (probably 60 GB?). If …

Bug_fix BGDIINF_SB-1850 large file upload via admin GUI

---

.dockerignore
.gitignore
scripts/create_large_dummy_asset_file.py

In order to test the upload of xxxxxxl sized dummy asset files (e.g. 60 GB), a simple script has been added.

BGDIINF_SB-1228 added a simple script for creating large asset files

---

app/tests/base_test.py
app/tests/test_serializer.py

We don't use stac_extension (see BGDIINF_SB-1410) there remove them from
unittest.

BGDIINF_SB-1765: Clean up unittest stac_extension

---

app/stac_api/pagination.py
app/stac_api/views.py
app/tests/base_test.py
app/tests/test_assets_endpoint.py
app/tests/test_collections_endpoint.py
app/tests/test_items_endpoint.py

For the view using pagination, the ordering is done in the pagination class.
This one did not had the ability to easily configure different ordering
per view. This has been added via the get_ordering() method which checks
for ordering attribute in the view.
For the assets ordering within items, we needed to do the ordering in
the prefetch related and in the get_queryset() because assets don't uses
pagination.
I don't think this have a big impact on performance but those needs definitely to be tested with k6.io.
NOTE: to avoid conflict with migrations files with the PR #299  this PR is based on feature_BGDIINF_SB-1863_publish_flag. Once #299 is merged I'll set the branch to `develop` before merging this one.

BGDIINF_SB-1864: Order API collections/items/assets by name

---

app/stac_api/apps.py

On prod we had some non authorized requests without content-type header
that crashed the service.

BGDIINF_SB-1898: Avoid crash if request is missing the content-type header.

---

Pipfile
Pipfile.lock
README.md
app/config/settings_prod.py
app/stac_api/serializers.py
app/stac_api/utils.py

Added related STAC Browser links in catalog, collection and item views.
Can be tested on DEV: https://service-stac.dev.bgdi.ch/api/stac/v0.9/

BGDIINF_SB-1959: Added STAC Browser links

---

spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml
spec/transaction/tags.yaml

Spec deployed here: https://service-stac.dev.bgdi.ch/api/stac/static/spec/v0.9/apitransactional.html#tag/Asset-Upload-Management

BGDIINF_SB-1981: updated spec for asset upload MD5 integrity check

---

README.md

removed link to dockerhub registry, dropped a few words on ECR instead.

Small adaptions of the README.md

---

.pylintrc
app/stac_api/apps.py
app/stac_api/managers.py
app/stac_api/models.py
app/stac_api/pagination.py
app/stac_api/s3_multipart_upload.py
app/stac_api/serializers.py
app/stac_api/validators_serializer.py
app/stac_api/validators_view.py
app/stac_api/views.py
app/stac_api/views_mixins.py
app/tests/test_asset_upload_endpoint.py
app/tests/test_asset_upload_model.py
app/tests/test_generic_api.py
app/tests/test_serializer.py
app/tests/test_serializer_asset_upload.py
app/tests/test_validators.py

Issue : md5_parts was an optional parameter while waiting for the users to adapt their scripts.
Fix: Now that those scripts are adapted, md5_parts is required for all uploads.
TODO: 
I'll check the tests, and ensure they work. 
I'll add a test that verifies that sending an upload request without the md5 fails

BGDIINF_SB-1983: `md5_parts` is now a mandatory parameter

---

app/stac_api/validators.py

Issue : Generic zip files were not accepted as media types
Fix : We accept those as media types

BGDIINF_SB-2033: adding generic zip media type

---

app/stac_api/serializers.py
app/stac_api/serializers_utils.py
app/stac_api/utils.py
app/stac_api/views.py
app/stac_api/views_mixins.py
app/tests/base_test.py
app/tests/test_serializer.py
spec/components/schemas.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/responses.yaml
spec/transaction/components/schemas.yaml

The parent link for a Collection or an Item, based on the STAC
spec should be respectively the landing page `/` (catalog) and the
collection `/<collection>` instead of the `/collections` and
`/collections/<collection>/items`. This is also required by the STAC
Browser, see (https://github.com/radiantearth/stac-browser/issues/105)
The generated links have also been consolidated in one method to
simplify the maintenance. For this simplification we base the generation
of the links based on the route name given in the urls.py. For the
DestroyMixin as it is used by several vues we could not use directly the
route name, therefore we added the route name to every view as name.

BGDIINF_SB-2083: Changed parent link to match STAC spec

---

Pipfile
Pipfile.lock
app/stac_api/utils.py

The STAC Browser links for the STAC-Browser v3 have changed. Although
the old links are redirected to the new link, we also changed them in the service. The new links are
- /browser/index.html/#/collections/COLLECTION
- /browser/index.html/#/collections/COLLECTION/items/ITEM
Also removed the base58 library from pip as it is not anymore directly
used by service STAC.

BGDIINF_SB-2210: Changed the STAC Browser links for Browser v3

---

app/stac_api/serializers_utils.py
app/stac_api/utils.py
app/tests/test_collections_summaries.py

For the collections page as well as the items list page, the STAC browser
links where not correct. The collection and item name where None.
With the v3 STAC browser there is no specific page for the items list.

BGDIINF_SB-2210: Fixed the STAC Browser links v3

---

app/config/settings_prod.py
app/tests/base_test.py
app/tests/test_landing_page.py

The STAC browser might tries to access the landing page without trailing slash:
`/api/stac/v0.9`
Which would be automatically redirected to `/api/stac/v0.9/` by the
`django.middleware.common.CommonMiddleware`.
Due to this we need to put the CORS header middleware before the `CommonMiddleware`
otherwise the redirect would not have the correct CORS headers and the STAC
Browser would not be able to access our API from another origin.

BGDIINF_SB-2713: Fixed CORS headers for landing page (STAC Browser)

---

Dockerfile
docker-compose-ci.yml

Fixed the worker tmp dir to a known directory in Dockerfile so that k8s can then mount a memory file system on that dir. This should increase performance at least by a factor 2.
Already deployed on dev last Friday.

BGDIINF_SB-2714: Dockerfile now sets worker_tmp_dir

---

app/stac_api/management/commands/write_perftests.py
app/stac_api/models.py
app/stac_api/serializers.py
app/stac_api/validators.py
app/tests/data_factory.py
app/tests/sample_data/asset_samples.py
app/tests/test_asset_model.py
app/tests/test_assets_endpoint.py
app/tests/test_validators.py

Before, the serializer only accepted exact matches. Now it accepts any
equivalent media types, i.e.:
- Optional spaces between the parameters
- Types, subtypes and parameter names are case insensitive
- Order of parameters not important
The database however still only accepts the "normalized" variant.

BGDIINF_SB-2707: Now serializer is more permissive with mime types

---

Dockerfile

The gunicorn temporary dir for worker should not be created and set by the
docker image but left to the deployment (aka k8s) which needs to ensure to have
it on tmpfs.
See also https://github.com/geoadmin/infra-kubernetes/pull/315

Fixed gunicorn tmp dir worker

---

app/stac_api/s3_multipart_upload.py
app/stac_api/views.py
app/tests/base_test.py
app/tests/test_asset_upload_endpoint.py
app/tests/utils.py

Only one asset upload is allowed at a time, before it used to automatically
abort ongoing upload when creating a new upload. The implementation had an
issue when multiple create upload happened on parallel, it crashed the service
due to race condition.
Making parallel or multiple create upload doesn't make sense as only one call
will be valid and the user will not know which one. E.g. if a user do two
requests in a row, both would have return 201 but only one of it would have
been valid and we could not ensure which one, could be the first or the second !
To avoid such random cases, we removed the auto abort mechanism. This means
that if multiple requests are sent at a time it is guarantied that only one
would be successful with 201 and valid. The others will returns 400 Bad Request
- …

BGDIINF_SB-2827: Removed auto abort asset upload on duplicate upload to fix integrity crash

---

spec/components/headers.yaml
spec/components/parameters.yaml
spec/components/responses.yaml
spec/components/schemas.yaml
spec/openapi.yaml
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/examples.yaml
spec/transaction/components/parameters.yaml
spec/transaction/components/responses.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml
spec/transaction/tags.yaml

This allow a user to upload data already compressed. This means that asset
compressed can only be in compressed form served.

BGDIINF_SB-2835: Added content_encoding in spec for asset upload

---

README.md
app/stac_api/management/commands/dummy_data.py
app/stac_api/views.py
app/tests/test_collections_endpoint.py

The collection paginations was broken because it was sorted by title and that
title could be missing or duplicates. For the cursor pagination it is a requirement
that the list is ordered by a unique existing column.
A first PR did fixed the issue by making the collection title required and unique
see #374. But because we have on PROD duplicate titles and that we need to keep
this functionality we revert the sorting by collection ID. See ticket for
more informations.

BGDIINF_SB-2813: Fixed collection pagination

---

Makefile

Issue : As Lifecycle policies in our docker repositories allow, for the moment, only prefixes to filter out images, local images without a prefix have to be pruned manually, which is not efficient.
Fix : When building local images, a `local-` prefix is added in front of the tag, which will enforce automatically self-cleaning policies for local images pushed to our docker repository.

BGDIINF_SB-2158: add local prefix in docker build

---

Makefile
spec/Makefile
spec/static/spec/v0.9/openapi.yaml
spec/static/spec/v0.9/openapitransactional.yaml

During the PR #371, the last commit of the PR; ad3f1e1da79659d9fb8aee9cf8382f6be61dae7e
removed some commented part, but the spec has not been built.
Because the build output is under source control and that the makefile used
the file as dependency, once this PR has been merged, running `make build-specs`
did nothing. However if you forced a build by removing the static
static/spec/v0.9/openapi.yaml and static/spec/v0.9/openapitransactional.yaml
files, it trigger a build with the modification of the last commit of #371.
Although on this case the spec did not really changed as it was just a code comment
clean up this can be dangerous as if user forget to build the spec and it gets
merged, the CI won't even notice it (the `make build-specs` of the CI would
do nothing). And we would notice …

Fixed build spec dependencies issues.

---

app/stac_api/apps.py
app/stac_api/exceptions.py
app/stac_api/s3_multipart_upload.py
app/stac_api/serializers.py
app/stac_api/views.py
app/tests/test_asset_upload_endpoint.py
spec/static/spec/v0.9/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

Now in case of a duplicate asset upload, it returns a 409 - conflict with the
current upload id in the answer.
This ease the error management for the user as it won't have to do a GET request to abort the current upload if needed.

BGDIINF_SB-2971: Changed the HTTP response to 409 in case of duplicate asset upload

---

app/middleware/logging.py

Since this morning, the collections and health check endpoint are returning 500. This is most likely caused by a special character in a newly updated collection description or ID field. The error is, decode cannot decode a byte 0xc3 in position 199: unexpected end of data. To prevent this, we now first decode the whole response.content and strip it afterwards, rather than the other way round.
This is the exact error message:
```json
"exc_text": "Traceback (most recent call last):\n  File \"/opt/service-stac/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"/opt/service-stac/app/middleware/logging.py\", line 57, in __call__\n    extra[\"response\"][\"payload\"] = …
```

PB-409: fix broken health check and collections endpoint

---

spec/components/schemas.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml

Adapt spec of item geometry to be one of point, lineString, polygon, multiPoint, multiLineString or multiPolygon.
This change is only in spec of v1, although the implementation is actually available in both v1 and v0.9.

PB-613: adapt spec for item geometry

---

spec/Makefile
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml

This should make it easier to inject things we need to use AWS API Gateway. It should also be a bit more robust and easier to use for external developers.

Clean up how we build the OpenAPI spec.

---

Makefile
Pipfile
Pipfile.lock

Use `test-debug` or `serve-debug` to start the tests or application in
debugmode. This will start the applications with debugpy. With following
configuration (launch.json) in vscode, this then allows for debugging in vscode:
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Python Debugger: Attach",
"type": "debugpy",
"request": "attach",
"justMyCode": false,
"connect": {
"host": "localhost",
"port": 5678
}
}
]
}
```
I was using this all the time recently and thought it might be useful for everybody. WDYT?

Added debugpy to the installation

---

app/stac_api/admin.py
app/tests/test_admin_page.py

Inline the collection assets to the collection's admin page.
The simplest, most straight forward implementation. Don't know whether the use case demands a better way. How many collection assets are usually in a collection?
I guess I could easily spend more time on this and create a custom template for this model, but on the other hand this will make it less dynamic in case of future changes..

PB-851 Inline the collection assets to collection in admin

---

app/tests/test_admin_page.py

/api/stac/admin always redirects so we don't actually know whether login succeeds when testing that endpoint. In this change we modify the test to point to /api/stac/admin/ which does return 200 when valid credentials are used and 302 when failing to log in. We also add a test to verify invalid credentials are correctly rejected/redirected.

Actually test that login works correctly.

---

app/stac_api/urls.py
app/stac_api/utils.py
app/stac_api/views.py

Add POST endpoint to run the management command to calculate the collection extents.
This is especially useful for e2e testing.
Should this be added to the spec and "officially" available?

PB-754: Endpoint to immediately calculate extent

---

Dockerfile
Makefile
README.md

docker-compose is obsolete. Instead we use the `docker compose` plugin
henceforth

PB-569 Switch from docker-compose to docker compose

---

app/stac_api/management/commands/calculate_extent.py

End-to-end test cases were flaky because the extent was sometimes not updated correctly.
The UNION operation does not guarantee order.
Add ORDER BY to make sure the NULL values are removed by LIMIT if there is another row.

PB-754: Fix extent calculation query

---

app/tests/tests_09/test_landing_page.py
app/tests/tests_10/test_landing_page.py

This test function assertion was added in https://github.com/geoadmin/service-stac/commit/54dca401bfcac33baf9cbf9fd8319bca253d6124 It only tests the redirection to the landing page but not the actual landing page.
This change ensures the landing page is also covered by this test.
It may make sense to test all the pages, which could be done in a separate change.

Test the CORS headers for the actual landing page.

---

docker-compose.yml

This removes the following warning when running `make setup`:
WARN[0000] docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

PB-569: Remove obsolete "version" from docker-compose.yml.

---

.pylintrc
app/stac_api/management/commands/dummy_data.py
app/stac_api/serializers.py
app/stac_api/utils.py
app/tests/utils.py

This fixes a bug in the pylintrc configuration. This also "fix" some broad exceptions either by using more specific ones or by disabling the check when I couldn't quickly find a more appropriate exception.

Make pylint overgeneral-exceptions check actually work.

---

app/config/admin.py
app/config/settings_prod.py
app/middleware/internal_redirect.py
app/tests/test_admin_page.py
app/tests/tests_09/test_landing_page.py
app/tests/tests_10/test_landing_page.py

API Gateway v1 strips trailing slashes from the request paths. We have a few endpoints that use trailing slashes. Specifically:
/api/stac/v1/
/api/stac/v0.9/
/api/stac/admin/*
Django's CommonMiddleware already has a feature to redirect URLs without trailing slash to their "slashed" equivalent when they exist. When combined with API Gateway v1 this causes a redirection loop.
This change introduces CommonMiddlewareWithInternalRedirect which handles the redirection internally to serve the query like if it had hit the "slashed" page directly.
It also updates the test to verify both endpoints work correctly.
Based on discussion in https://ltwiki.adr.admin.ch:8443/display/~adrien.kunysz@swisstopo.ch/STAC+API+trailing+slash+inconsistency

PB-796: handle paths without trailing slash without redirection.

---

app/tests/tests_09/test_cf_forwarded_proto.py
app/tests/tests_10/test_cf_forwarded_proto.py

Since "https" does start with "http", `'https'.startswith('http')` is not a useful test. This change ensures we test for "https://" and "http://" respectively.

PB-612: actually test links start with http(s)://

---

app/tests/tests_09/base_test.py
app/tests/tests_09/test_serializer.py
app/tests/tests_10/base_test.py
app/tests/tests_10/test_serializer.py

The serializer test involve comparing the "created" and "updated" fields of collections. These fields are populated with whatever Django thinks is the current time. Until this PR, the tests assumed that comparing to "test start time" +/- 2 seconds was good enough. As per PB-694 this has proved wrong several times.
This change updates the tests such that we only verify the field values are between the start time and end time of each test. As long as time goes forward this should be fine. In any case, it should already make the test much more reliable.
We verified this works by adding a 5 seconds delay after the start of the test (which was removed in the second to last change in this PR).

Deflake serializer tests.

---

Pipfile
Pipfile.lock
app/config/logging-cfg-local.yml
app/config/settings_prod.py

Add middleware and logging filter to add the django request to all log records.
Also see: https://github.com/geoadmin/lib-py-logging-utilities/pull/62

PB-511: Add request context to all logs

---

spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/responses.yaml
spec/transaction/paths.yaml
spec/transaction/tags.yaml

Add CRUD endpoints for collection level assets.
Add endpoints for collection asset upload management. As process for upload is the same as for feature assets, only link to description.

PB-755: Spec for collection assets

---

app/middleware/logging.py

The request body is in utf-8 which needs either 1 byte or 2 bytes per character
depending on the character, so we need to decode first before truncating otherwise
we might truncate in the middle of a utf-8 character and it will break the decode.

PB-932: Avoid UTF-8 truncation in logging

---

README.md
secrets.yml

Use the params from the SSM store instead of gopass for instantiating the database.
(Since we already have the databases set up this is done rather for completeness sake than actual usage. We probably won't actually use these params in the near future. Also, the Database will be [managed by TF](https://jira.swisstopo.ch/browse/PB-986))
See https://github.com/geoadmin/infra-terraform-bgdi/pull/410 for more context.

PB-950 Switch to using ssm params - #minor

---

app/stac_api/views/item.py

Endpoint to get list of items is sometimes slow. This is due to the sql query that the postgresql planner does not optimize properly, even though the indexes seem to be set as expected. Using a subquery to filter greatly improves the performance (up to 1 second reduction in query execution time).
The following EXPLAIN ANALYZE queries were run on INT with postgres v16.4 using the collection _ch.swisstopo.swisstlm3d_.
EXPLAIN ANALYZE before change:
````
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT
"stac_api_item"."id",
"stac_api_item"."name",
"stac_api_item"."collection_id",
"stac_api_item"."geometry" :: bytea,
"stac_api_item"."created",
"stac_api_item"."updated",
"stac_api_item"."properties_datetime",
"stac_api_item"."properties_start_datetime",
"stac_api_item"."properties_end_datetime", …
```

PB-962: Improve performance to list items

---

app/tests/test_multiple_bucket_setup.py

A little attempt to have at least *some* way to test if the pattern in the service itself works. I try to think of other possibilities, so that we don't have to change the code of `service-stac` each time we migrate a collection, but I guess this is OK for one time.

PB-1008 Test the ch.are pattern

---

app/config/settings_dev.py
app/middleware/apigw.py
app/tests/test_admin_page.py

We are delegating the authentication to API Gateway which sets the
`Geoadmin-Username` header. However due to how API Gateway and JWT-based
authentication work, the header is only set at login time. It is on the service
to keep track of the user afterwards.
This change updates service-stac in Dev to trust the `Geoadmin-Username` header
if it is present. Then service-stac persists the user across their whole session.
Relevant documentation is at https://docs.djangoproject.com/en/5.1/howto/auth-remote-user/

PB-1009: trust API Gateway to authenticate users.

---

app/stac_api/views/collection.py
spec/components/parameters.yaml
spec/openapi.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml

The response from the /collections route can now be filtered by provider. The get method of COllectionList has also been re-factored to reduce code repetition.
In order to achieve this, filter_queryset has been overwritten in CollectionList to read the provider argument and filter the dataset accordingly.

PB-224: Added a query parameter on the /collections route to filter by provider

---

Dockerfile

The debug Docker image does not include the static files. This means that when
we run it in Kubernetes (in the dev staging), it fails to serve some requests.
This make debugging and testing harder than it needs to be.
This change updates Dockerfile to include the static files in the debug image.
As per commit, this PR also includes some Dockerfile style fix.

PB-1238: include static files in debug image.

---

app/middleware/apigw.py

As per discussion in https://code.djangoproject.com/ticket/35971
Instead of copy/pasting `process_request` from the parent class, we can just drop the `Geoadmin-Username` header from `request.META` if `Geoadmin-Authenticated` is not true before calling `process_request` from the parent class.

PB-1009: simplify ApiGatewayMiddleware.

---

app/stac_api/management/commands/update_asset_file_size.py

Make it possible to only update a chunk of assets at once, so the command will hopefully stop timing out. I'm attempting to solve the problem by re-running the command a couple of times, maybe in a temporary cronjob.
Also excluded the external assets and improved the output a bit.
Running this command every 60 seconds with 1000 assets at once should result in a completion after 30h. I will have to figure out a sensible chunk size.
Of course it's 1000 assets and 1000 collection assets, but there are only 2 CollectionAssets on prod 😂

PB-1091 Add count to size updater, exclude is_external

---

spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/parameters.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

This adds a section for a new endpoint in the OpenAPI docs:
- endpoint: `POST collections/{collectionId}`
- docs on local web server: http://0.0.0.0:8090/apitransactional.html#tag/Data-Management/operation/bulkUpsertItems
Some notes:
1. The term "bulk" was used instead of "batch" after looking up the difference in [a blog post](https://www.codementor.io/blog/batch-endpoints-6olbjay1hd):
> It should be noted that some people, such as [John Apostolidis](http://apostolidis.me/bulk-operations/), make a hard distinction between bulk processing (applying the same operation to multiple entries) and batch processing (applying potentially different operations to different entries). While it makes sense to have this distinction, in reality, the two ideas are often conflated and used …

PB-1293 Add docs for endpoint bulkUpsertItems

---

spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml

Ever since https://github.com/geoadmin/service-stac/commit/cc331f241b59fbc798a65bb95b2fb6a5ef739fd5 the output of build-specs has been inconsistent with what is in the repo. This change commits the output of "make build-specs".
A later change will attempt to re-enable ci-build-check-specs as that was disabled in https://github.com/geoadmin/service-stac/pull/389/commits/32439dd1c342b97029c0b6b42516562c58829f38 and 611d339a2d7d3993152cdaf039cef4d670539c43 probably resolved the issue.

Regenerate the specs.

---

app/stac_api/management/commands/update_asset_file_size.py

For some assets the file on the bucket is missing. This makes the file_size_upgrade cronjob be stuck in a infinite loop, as it'll always try to update the next N assets.
Therefore we flag these assets with a `file_size` of `None`, to avoid repeating the update and to be able to produce a list of missing files.

PB-1091 Flag the inexistent files in the file size updater

---

app/config/settings_dev.py
app/config/settings_prod.py
app/middleware/apigw.py
app/tests/test_admin_page.py

Adds a flag `FEATURE_AUTH_ENABLE_APIGW` to the django settings to enable ApiGateway authentication. The flag is `false` by default (authentication is disabled) and can be set using an environment variable with the same name.
Details:
- I've moved the ApiGateway middleware and backend to `settings_prod`, as this is the base for all scenarios/builds. The middleware and new backend now check for the feature flag.
- `RemoteUserMiddleware` would add an authenticated user to the request if not already there (see [here](https://github.com/django/django/blob/4cad317ff1f9a79d54c1d5b12f1ccbd260ca009f/django/contrib/auth/middleware.py#L111)). Dropping out early in `ApiGatewayMiddleware` seems sufficient to disallow ApiGateway authentication if disabled.
- `RemoteUserMiddleware` uses …

PB-1281: Add feature flag for ApiGateway authentication

---

app/tests/tests_09/test_search_endpoint.py
app/tests/tests_10/test_search_endpoint.py

Unit tests should not do a login for the search endpoint since it's public.

Do not login when testing search endpoint

---

app/config/settings_prod.py
app/middleware/rest_framework_authentication.py
app/tests/tests_10/test_asset_upload_endpoint.py
app/tests/tests_10/test_assets_endpoint.py
app/tests/tests_10/test_collection_asset_upload_endpoint.py
app/tests/tests_10/test_collection_assets_endpoint.py
app/tests/tests_10/test_collections_endpoint.py
app/tests/tests_10/test_items_endpoint.py

Disables Basic / Token / Session Auth for STAC v1 if `FEATURE_AUTH_RESTRICT_V1` is set.
Together with `FEATURE_AUTH_ENABLE_APIGW` authentication is as followed:
| Authentication | STAC v0.9                       | STAC v1.0                       |
| ---------- | ------------------------- | ------------------------- |
| Basic      | yes                       | FEATURE_AUTH_RESTRICT_V1  |
| Token      | yes                       | FEATURE_AUTH_RESTRICT_V1  |
| Session    | yes                       | FEATURE_AUTH_RESTRICT_V1  |
| ApiGateway | FEATURE_AUTH_ENABLE_APIGW | FEATURE_AUTH_ENABLE_APIGW |

PB-1281: Disable old authentication for STAC v1

---

app/stac_api/admin.py
app/stac_api/models/general.py
app/stac_api/serializers/item.py
app/tests/tests_10/test_external_assets_endpoint.py

Providing the means to filter out assets that are 
a) in progress, where the asset is created but the upload isn't done yet
b) that weren't found on the s3 bucket while updating the `file_size` in the cronjob (see https://github.com/geoadmin/service-stac/pull/484 and https://github.com/geoadmin/service-stac/pull/464/files for reference)
This filter will start making sense after the file_size update cronjob ran through (should be the case by the end of the week). After that, every file that has a `file_size` of 0 will signify that it isn't uploaded yet. 
Slightly adjusting the process for external assets: we set the file size to -1 as we currently can't determine the real size. Could maybe be done by refactoring the check asset call out of the validator, in order to parse the …

PB-1360 Improve internal upload workflow

---

app/stac_api/serializers/item.py
app/stac_api/validators_serializer.py
app/stac_api/views/item.py
app/tests/tests_09/test_items_endpoint.py
app/tests/tests_10/test_items_endpoint.py
app/tests/tests_10/test_serializer.py
spec/components/schemas.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

Add a new POST endpoint to `collections/{collectionId}/items` that lets you create multiple Items together with their assets at in one go.
Explicitly handled HTTP return status:
- 201 Created: Successful creation
(!) Even for empty list of items
- 400 Bad Request:
- Payload malformed
- Item exists already
- Over 100 items
- No or empty HTTP header parameter "Idempotency-Key"
- 404 Not Found: Collection not found
Example payload:
```json
{
"features": [
{
"id": "feature-1",
"links": [...],
"assets": {
"asset-1-1.txt": {...},
"asset-1-2.txt": {...},
},
"geometry": {...},
"properties": {...},
"stac_extensions": [...]
},
{
"id": "feature-2",
"links": [...],
"assets": {
"asset-2-1.txt": {...},
"asset-2-2.txt": {...},
},
"geometry": {...},
"properties": {...},
"stac_extensions": [...]
}
]
}
``` …

PB-1279 Batch create endpoint for items/assets

---

app/tests/tests_10/test_items_endpoint.py

CC @boecklic 
Turns out this only happens during tests because of django wrapping the whole test in a transaction:
```
START TRANSACTION
SAVE ITEM --> IntegrityError because of existing unique constraint
SAVE SESSION --> DatabaseError because of an error occured in the current transaction
END TRANSACTION
```
Using a `TransactionalTestCase` instead of a `TestCase` solves the issue.
Posting outside works as expected:
```bash
curl \
--include \
--request POST \
--header "Geoadmin-Username: apiuser" \
--header "Geoadmin-Authenticated: true" \
--header "Idempotency-Key: abc-123" \
--url http://localhost:8000/api/stac/v1/collections/test/items \
--header 'Content-Type: application/json' \
--data '{
"features": [{
"id": "test.geojson",
"assets": [{
"id": "asset-1.txt",
"title": "My title 1", …
```

PB-1279: Fix test

---

app/stac_api/serializers/utils.py
app/tests/tests_10/test_items_endpoint.py
app/tests/tests_10/test_serializer.py

nested asset deserialization accepts now the same format as the result of the serialization, i.e. a dict. This is now also compliant to the spec.
@adk-swisstopo and @asteiner-swisstopo I've put you both as reviewers, Alex initially developed but is away so I hope Adrien can review.

PB-1478 made asset deserialization equivalent to serialization

---

.gitignore
.vscode/settings.json

Those workspace settings are required in order to make use of vscode unittest tab. This helps debugging application.

Added vscode setting to run unittest from vscode

---

app/stac_api/templates/js/admin/upload.js

In PB-1229 we started routing all STAC traffic through API Gateway which restricts the size of requests. In PB-1331 we updated the admin UI upload page to use S3 URLs for upload such that large requests don't go through API Gateway any more. This uses v1 API endpoints from Javascript. In PB-1281 we disabled session authentication for v1 endpoints, thus breaking admin UI upload page. In PB-1380 we opened v1 in PROD.
We prefer to not re-enable session authentication for v1 because disabling it later will be harder as (more) users would start relying on it. Current workaround involves uploading assets on behalf of users with our own script using the API.
This change updates the Javascript to use v0.9 API endpoints which still accept session-based authentication. This is a temporary …

PB-1469: use v0.9 for large uploads from admin UI.

---

spec/components/responses.yaml
spec/components/schemas.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml
spec/transaction/components/responses.yaml
spec/transaction/components/schemas.yaml
spec/transaction/paths.yaml

We still have many references (mostly in examples) to v0.9 in the spec.
They are all replaced with v1 with this PR using a search and replace.
This PR superseed #520.

Updated all paths from v0.9 to v1 in openapi spec

---

app/stac_api/templates/js/admin/upload.js

There are multiple problems preventing non-ASCII files from being uploaded correctly. Specifically:
* the content of the file was converted to UTF-8 before upload;
* the content of the file was converted to UTF-8 before MD5 hashing (for S3);
* the content of the file was converted to UTF-8 before SHA-256 hashing (for STAC).
None of these conversion was appropriate and resulted in mangled file and incorrect hashes. This PR removes them.

PB-1469: fix charset conversion for large file upload.

---

app/stac_api/templates/js/admin/upload.js
app/templates/uploadtemplate.html

Specifically:
* actually attempt to abort abandoned uploads before starting a new one (does not actually work well depending on cache state but better than not working at all);
* document the actual size limit (~512MB).
This is still far from ideal but strictly before than the current state.

Make large uploads a little more useable.

---

docker-compose.yml

When entering manually docker compose up it uses random ports and DB name.
So now it uses the same as the .env.default file.

Allow to use docker compose up directly

---

.env.default

Those session settings are required in order to have our E2E tests from
infra-e2e-tests repos to pass when running them using the localhost setup.
See also https://github.com/geoadmin/infra-e2e-tests/pull/344

Fixed E2E tests for the localhost

---

app/config/logging-cfg-local.yml

The user's username is now logged whenever a request is made. This works for all authenticated requests which use the Geoadmin-Username (Cognito) header.
Preview : 
`'user' : { 'username' : 'apiuser' }`

PB-929 : added Cognito username logging for requests

---

app/stac_api/admin.py
app/stac_api/models/collection.py
app/stac_api/widgets/label_widget.py

The 'file' field has been added back to the Collections and CollectionsAsset form after I removed in the previous PR.
UPDATE : I also found a better implementation for removing the upload button, which involves simply setting the 'file' field as read-only by default, and only making it editable for external assets. This also solves the missing href problem we had with the custom widget. 
LabelWidget has therefore been removed.

PB-1434 : Add back 'file' field to Collections and CollectionAssets

---

app/stac_api/management/commands/remove_expired_items.py
app/stac_api/models/item.py
app/stac_api/serializers/item.py
app/stac_api/validators.py
app/tests/tests_09/test_validators.py
app/tests/tests_10/test_assets_endpoint.py
app/tests/tests_10/test_item_model.py
app/tests/tests_10/test_items_endpoint.py
app/tests/tests_10/test_remove_expired_items.py
app/tests/tests_10/test_validators.py

In the forecast extension, `datetime` is the forecast date. So `datetime` can be anywhere in the future and `expires` might be before that. So comparing these two dates makes no sense. Same for `end_datetime`.
The `expires` field is part of the Timestamps extension, so it might be used in different contexts where this check would actually make sense. But ultimately, it is the responsibility of the data owner that the data is consistent. So we remove the check to reduce complexity on our side.
:information_source:  The definition of the fields according to the [forecast extension docs](https://github.com/stac-extensions/forecast?tab=readme-ov-file#additional-fields-from-other-extensions):
> - **datetime**: REQUIRED. The forecast datetime. It follows the definition in the [STAC Common …

PB-1495 Remove date comparison for property `expires`

---

app/stac_api/admin.py
app/stac_api/serializers/item.py
app/stac_api/validators.py
app/stac_api/views/item.py
app/tests/tests_10/test_items_endpoint.py
app/tests/tests_10/test_serializer.py

This removes the prefix `https://sys-data.int.bgdi.ch` from the `href` field of assets uploaded via [the bulk upload](https://sys-data.int.bgdi.ch/api/stac/static/spec/v1/apitransactional.html#tag/Data-Management/operation/bulkCreateItems).
This happened because there was no `is_external` flag set when validating the `href` field from a payload. If this flag is not set, the validation builds it's own URL. This URL is prefixed with our internal hostname, e.g. `https://sys-data.int.bgdi.ch` for INT or `https://testserver` for local development. So ended up having all `href` prefixed with the `https://sys-data.int.bgdi.ch`.
The special treatment of assets' `href` was introduced in [PB-35 external asset URL](https://swissgeoplatform.atlassian.net/browse/PB-35), that is why I set @schtibe as …

PB-1519 Issue with asset href extra prefix

---

README.md
app/wsgi.py

This is controlled by the `GUNICORN_DUMP_STACKS_ON_EXIT` environment variable.
As gunicorn insists on doing its own signal handling, we cannot use [faulthandler](https://docs.python.org/3/library/faulthandler.html)).
As we use the gevent asynchronous workers model, we need to use the special [gevent stack dumping mechanism](https://www.gevent.org/api/gevent.util.html#gevent.util.format_run_info) (i.e. not the regular [traceback](https://docs.python.org/3/library/traceback.html)) to get something useful.
Upon
[liveness probe failure](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes), [Kubernetes sends a `SIGTERM`](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) to the master, waits …

Add ability to log stack traces on exit.

---

app/wsgi.py

We often see deadlocks involving urllib3's connection pool queue. Its looks likely to be related to https://github.com/gevent/gevent/issues/1957#issuecomment-1900138350 A workaround suggested in that issue is to explicitely patch `urllib3.ConnectionPool.QueueCls` after the call to `gevent.monkey.patch_all`.
This change does that, guarded by the `GEVENT_PATCH_URLLIB3_CPOOL_QUEUE` environment variable.

Attempt to work around gevent/urllib3 deadlock.

---

README.md
app/wsgi.py

In https://github.com/geoadmin/service-stac/pull/558 we added the ability to log stack traces upon exit. However we did not distinguish between a normal graceful exit and an abnormal exit of a deadlocked service. This means that on every exit/restart, we clutter the logs with stack traces.
With this change, upon exit we only attempt to dump the stack if the worker is still running after a delay. This means that graceful exit that complete within that delay do not clutter the logs with stack traces.
This change removes the `GUNICORN_DUMP_STACKS_ON_EXIT` variable and adds `GUNICORN_STACK_DUMP_DELAY` and `GUNICORN_GRACEFUL_TIMEOUT`. The former being set by default to one second less than the latter. We may need to tweak `GUNICORN_GRACEFUL_TIMEOUT` to be coherent with the Kubernetes …

PB-1531: only dump stacks when exit is taking too long.

---

app/stac_api/signals.py

Every time we delete an `Asset` or `CollectionAsset`, we make a call to the corresponding S3 `DeleteObjects` method. For objects that are hosted externally (i.e. not in an S3 bucket we control), this call always fails silently and we can just as well not do it.
With this change, we stop attempting to call `DeleteObjects` for externally hosted `Assets` and `CollectionAssets`, thus speeding up deletion.

PB-1575: don't attempt to delete externally hosted S3 objects.

---

app/config/settings_prod.py
app/stac_api/validators_view.py
app/stac_api/views/filters.py
app/stac_api/views/general.py
app/stac_api/views/item.py
app/tests/tests_10/test_search_endpoint.py

This hides expired items in the `/search` endpoints. That this wasn't done already only became apparent when a bug prevented the cron job `cron-delete-expired` to clean up expired items properly, see PB-1575.
There are two search endpoints affected by this change:
1. [GET /search](https://sys-data.dev.bgdi.ch/api/stac/static/spec/v1/apitransactional.html#tag/STAC/operation/getSearchSTAC): Simple filtering
2. [POST /search](https://sys-data.dev.bgdi.ch/api/stac/static/spec/v1/apitransactional.html#tag/STAC/operation/postSearchSTAC): Advanced filtering in the payload.
We hide an item if has property "expires" set to a time in the past, so in principle the same as in these endpoints:
- [GET /collections/{collectionId}/items](https://sys-data.dev.bgdi.ch/api/stac/static/spec/v1/apitransactiona …

PB-1635 Hide expired items in search

---

app/stac_api/exceptions.py
app/stac_api/managers.py
app/stac_api/migrations/0067_update_conformance.py
app/stac_api/pagination.py
app/stac_api/utils.py
app/stac_api/validators_serializer.py
app/tests/tests_09/test_generic_api.py
app/tests/tests_09/test_items_endpoint_bbox.py
app/tests/tests_10/test_generic_api.py
app/tests/tests_10/test_items_endpoint_bbox.py
app/tests/tests_10/test_search_endpoint.py
spec/components/parameters.yaml
spec/openapi.yaml
spec/static/spec/v1/openapi.yaml
spec/static/spec/v1/openapitransactional.yaml

Add item search-conformance. We still are missing a couple of points to be 100% conform to the spec, however for our use cases it is close enough and still helpful to add the item-search to our conformance list.
Missing conformance:
- Return Content-Type Header is not `application/geo+json`. This would be a breaking change
- Filter by 3d bbox (bbox with 6 values). Not a trivial change.
Changes:
- If limit is larger than the configured max_limit, use max_limit instead of returning status 400
- According to https://github.com/radiantearth/stac-api-spec/blob/release/v1.0.0/item-search/README.md#query-parameter-table
- Datetime is case insensitive
- Filter by intersect in GET request, as is the case with a POST request
- If bbox has 6 values, return status 501 and custom error message …

PB-1590: Added item-search conformance - #minor

---

app/middleware/cors.py
app/tests/tests_09/base_test.py
app/tests/tests_09/test_generic_api.py
app/tests/tests_10/base_test.py
app/tests/tests_10/test_generic_api.py

currently stac-service in edge with strict mode enabled refuses to load from other pages due to CORS error.
**repro of error case**
1. use edge in strict mode (i.e. federal default setup)
2. open https://radiantearth.github.io/stac-browser/#/external/data.geo.admin.ch/api/stac/v0.9/?.language=en
3. see error message 
4. check console log
`
Access to XMLHttpRequest at 'https://data.geo.admin.ch/api/stac/v0.9/' from origin 'https://radiantearth.github.io' has been blocked by CORS policy: Request header field accept-language is not allowed by Access-Control-Allow-Headers in preflight response.
`
**measures to enable edge in strict mode**
HTH to enable data.geo.admin.ch STAC-service for broader internal & public use 😄

fix: update Access-Control-Allow-Headers for edge using `Accept-Language` header longer 128

---

Pipfile
Pipfile.lock

Before this change we were using psycopg 2.9.10. This does not seem to be designed to [work correctly with gevent](https://www.psycopg.org/docs/advanced.html#support-for-coroutine-libraries) "out of the box". The [psycogreen](https://github.com/psycopg/psycogreen/) library was written to resolve that problem but we don't seem to be using it at all.
Upgrading to [psycopg 3 allows proper integration with gevent](https://www.psycopg.org/psycopg3/docs/advanced/async.html#gevent-support) without psycogreen or other workaround.
This change upgrades service-stac from psycopg 2.9.10 to 3.2.9. This was done by updating the Pipfile then running `pipenv install`. This also updated other dependencies.
In local tests, I verified the `/checker` endpoint remains much more responsive with this change …

PB-1785: upgrade to psycopg 3.

---

README.md
app/config/settings_prod.py
app/config/urls.py
app/tests/test_checker.py

We want to add a readiness probe and update the liveness probe to be more tolerant of slow responses. In order to verify this works as expected, we need to be able to inject arbitrary delays in checker responses.
This change adds a `CHECKER_DELAY` setting that allows delaying the `/checker` endpoint by a commensurate number of seconds. This also adds previously missing unit test against the checker endpoint.

PB-1788: add way to slow down checker endpoint.

---

README.md
app/wsgi.py

The default is 2 and not really suitable when we have a reverses proxy in front with a higher idle connection timeout.
This PR also includes a small Markdown syntax fix for the README.

PB-1943: make keepalive timeout configurable.
